"""Study plan models — the companion's plan that drives daily learning."""
import uuid
from datetime import datetime

from sqlalchemy import String, Text, DateTime, Integer, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


class LearningPlan(Base):
    """A study plan generated by the companion agent."""
    __tablename__ = "learning_plans"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(String(36), index=True)
    title: Mapped[str] = mapped_column(String(128), default="")
    goal: Mapped[str] = mapped_column(Text, default="")
    summary: Mapped[str] = mapped_column(Text, default="")       # AI 生成的总体说明
    total_days: Mapped[int] = mapped_column(Integer, default=7)
    status: Mapped[str] = mapped_column(String(16), default="active")  # active / completed / paused
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class PlanTask(Base):
    """A concrete daily task on a plan."""
    __tablename__ = "plan_tasks"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    plan_id: Mapped[str] = mapped_column(String(36), ForeignKey("learning_plans.id"), index=True)
    day_index: Mapped[int] = mapped_column(Integer, default=1)   # 第几天 (1-based)
    scheduled_date: Mapped[str | None] = mapped_column(String(16), nullable=True)  # YYYY-MM-DD
    title: Mapped[str] = mapped_column(String(160), default="")
    description: Mapped[str] = mapped_column(Text, default="")
    task_type: Mapped[str] = mapped_column(String(16), default="learn")  # learn / practice / review / chat
    document_id: Mapped[str | None] = mapped_column(String(36), nullable=True)  # 关联的学习资料
    status: Mapped[str] = mapped_column(String(16), default="todo")  # todo / done / skipped
    completed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
