#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""计算机二级公共基础知识选择题（Python/C/Office 通用，选择 40 分里那 10 分）。

按高频考点编写：算法、数据结构（栈/队列/树/二叉树）、排序查找、计算机基础、
软件工程、数据库。答案唯一明确，供选择题判分精确匹配。
"""

PUBLIC_BASE_QUESTIONS = [
    # ── 算法 ──
    {"qtype": "choice",
     "question": "算法的时间复杂度是指（）",
     "options": ["算法执行过程中所需要的基本运算次数", "执行算法程序所需要的时间", "算法执行过程中所需存储空间的多少", "算法程序的长短"],
     "answer": "算法执行过程中所需要的基本运算次数",
     "explanation": "时间复杂度衡量基本运算次数（与问题规模 n 相关）；存储空间是空间复杂度，不是时间。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "算法的基本特征不包括（）",
     "options": ["灵活性", "确定性", "有穷性", "可行性"],
     "answer": "灵活性",
     "explanation": "算法的基本特征：有穷性、确定性、可行性、拥有足够的情报；灵活不是算法特征。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "算法的有穷性是指（）",
     "options": ["算法必须在有限步骤内结束", "算法必须包含有限个数据", "算法的每个步骤必须有限长", "算法的输入必须是有限个"],
     "answer": "算法必须在有限步骤内结束",
     "explanation": "有穷性 = 算法在执行有限步之后必须终止，不能无限循环。",
     "source_text": ""},
    # ── 数据结构 ──
    {"qtype": "choice",
     "question": "下列属于非线性结构的是（）",
     "options": ["二叉树", "线性表", "栈", "队列"],
     "answer": "二叉树",
     "explanation": "二叉树是一对多的层次结构，属非线性；线性表、栈、队列都是一对一的线性结构。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "下列关于栈的叙述，正确的是（）",
     "options": ["栈按“先进后出”原则组织数据", "栈按“先进先出”原则组织数据", "栈只能在底部插入和删除", "栈顶元素是最先插入的元素"],
     "answer": "栈按“先进后出”原则组织数据",
     "explanation": "栈（stack）后进先出 LIFO，只能在栈顶插入/删除；先进先出是队列。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "队列（queue）中数据的进出原则是（）",
     "options": ["先进先出", "先进后出", "后进先出", "随机存取"],
     "answer": "先进先出",
     "explanation": "队列先进先出 FIFO，一端入队一端出队；后进先出的是栈。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "下列关于线性表的叙述，正确的是（）",
     "options": ["线性表是元素之间具有一对一逻辑关系的线性结构", "线性表的元素之间是一对多关系", "线性表只能顺序存储", "线性表就是数组"],
     "answer": "线性表是元素之间具有一对一逻辑关系的线性结构",
     "explanation": "线性表元素一对一；它既可以顺序存储也可以链式存储，不等同于数组。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "在深度为 k 的满二叉树中，叶子结点的个数是（）",
     "options": ["2^(k-1)", "2^k", "2^(k-1)-1", "2^k-1"],
     "answer": "2^(k-1)",
     "explanation": "满二叉树第 k 层（叶子层）有 2^(k-1) 个结点；整棵满二叉树结点总数为 2^k-1。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "对一棵二叉树进行中序遍历，其访问顺序是（）",
     "options": ["左子树 → 根 → 右子树", "根 → 左子树 → 右子树", "左子树 → 右子树 → 根", "根 → 右子树 → 左子树"],
     "answer": "左子树 → 根 → 右子树",
     "explanation": "中序：左-根-右；先序：根-左-右；后序：左-右-根。记口诀「左右根看中间」。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "循环队列的队满条件取决于（）",
     "options": ["队头指针与队尾指针的相对位置", "队列中元素的值", "队列的长度固定不变", "队头指针是否指向数组最后一个元素"],
     "answer": "队头指针与队尾指针的相对位置",
     "explanation": "循环队列用头、尾两个指针判断队空/队满，与元素值无关。",
     "source_text": ""},
    # ── 查找与排序 ──
    {"qtype": "choice",
     "question": "在长度为 n 的线性表中进行顺序查找，最坏情况下需要比较的次数是（）",
     "options": ["n", "n/2", "log n", "n²"],
     "answer": "n",
     "explanation": "顺序查找最坏情况是目标在末尾或不存在，需比较 n 次；平均约 n/2。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "对长度为 n 的有序线性表进行二分查找，最坏情况下需要比较的次数是（）",
     "options": ["log₂n", "n", "n/2", "n²"],
     "answer": "log₂n",
     "explanation": "二分查找每次砍半，最坏比较次数约为 log₂n；顺序查找才是 n。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "下列排序算法中，最坏情况时间复杂度最低的是（）",
     "options": ["堆排序", "冒泡排序", "快速排序", "简单插入排序"],
     "answer": "堆排序",
     "explanation": "堆排序最坏 O(n log n)；冒泡、快速（最坏）、简单插入最坏都是 O(n²)。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "下列排序算法中，最坏情况下时间复杂度为 O(n²) 的是（）",
     "options": ["快速排序", "堆排序", "归并排序", "基数排序"],
     "answer": "快速排序",
     "explanation": "快速排序平均 O(n log n)，但最坏（基本有序）退化为 O(n²)；堆/归并最坏都是 O(n log n)。",
     "source_text": ""},
    # ── 计算机基础 ──
    {"qtype": "choice",
     "question": "计算机完成一条指令所花费的时间称为（）",
     "options": ["指令周期", "机器周期", "时钟周期", "存取周期"],
     "answer": "指令周期",
     "explanation": "指令周期 = 取出并执行一条指令所需时间；时钟周期最小，机器周期居中。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "CPU 要读取外存储器中的信息，必须先将其调入（）",
     "options": ["内存储器", "高速缓存", "寄存器", "光盘"],
     "answer": "内存储器",
     "explanation": "外存信息必须先调入内存，CPU 才能直接访问。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "运算器的基本功能是（）",
     "options": ["进行算术运算和逻辑运算", "存放数据和程序", "控制指令的执行顺序", "管理输入输出设备"],
     "answer": "进行算术运算和逻辑运算",
     "explanation": "运算器负责算术（加减乘除）和逻辑（与或非比较）运算；控制器负责指挥控制。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "整数在计算机中存储和运算通常采用（）格式",
     "options": ["补码", "原码", "反码", "ASCII 码"],
     "answer": "补码",
     "explanation": "整数一般用补码存储，方便统一加减法；ASCII 码用于字符。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "总线的数据传输率也称为（）",
     "options": ["总线带宽", "总线宽度", "总线频率", "总线周期"],
     "answer": "总线带宽",
     "explanation": "总线带宽 = 单位时间内总线上传送的数据量（数据传输率）。",
     "source_text": ""},
    # ── 软件工程 ──
    {"qtype": "choice",
     "question": "数据流图（DFD）主要用于表达（）阶段的需求",
     "options": ["需求分析", "概要设计", "详细设计", "编码实现"],
     "answer": "需求分析",
     "explanation": "DFD 用于需求分析阶段，描述数据在系统中的流向和处理。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "结构化程序设计的三种基本结构是（）",
     "options": ["顺序、选择、循环", "顺序、分支、递归", "选择、循环、跳转", "顺序、循环、转移"],
     "answer": "顺序、选择、循环",
     "explanation": "结构化程序设计只用顺序、选择、循环三种结构，保证程序清晰。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "在软件开发中，属于生命周期「定义阶段」的活动是（）",
     "options": ["需求分析", "代码编写", "软件测试", "软件维护"],
     "answer": "需求分析",
     "explanation": "软件生命周期分定义（问题定义、可行性、需求分析）、开发（设计、编码、测试）、维护三阶段。",
     "source_text": ""},
    # ── 数据库 ──
    {"qtype": "choice",
     "question": "数据库管理系统（DBMS）的核心功能是（）",
     "options": ["数据定义与数据操作", "数据压缩", "数据加密", "数据打印"],
     "answer": "数据定义与数据操作",
     "explanation": "DBMS 核心是数据定义（DDL）与数据操作（DML），负责数据的管理、控制。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "关系数据库中，一个关系对应一张（）",
     "options": ["二维表", "一维数组", "链表", "二叉树"],
     "answer": "二维表",
     "explanation": "关系模型用二维表表示数据，一行一个元组（记录），一列一个属性（字段）。",
     "source_text": ""},
    {"qtype": "choice",
     "question": "数据库系统的三级模式结构是指（）",
     "options": ["外模式、模式、内模式", "外模式、概念模式、逻辑模式", "模式、子模式、物理模式三个层次之外还有存储", "用户模式、管理员模式、系统模式"],
     "answer": "外模式、模式、内模式",
     "explanation": "三级模式：外模式（用户视图）、模式（概念）、内模式（物理存储）。",
     "source_text": ""},
]
